<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFrameworks />
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SendPulser.Sample.Web</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/SendPulser.AspNetCore/SendPulser.AspNetCore.csproj" />
    <ProjectReference Include="../../src/SendPulser.Resilience/SendPulser.Resilience.csproj" />
  </ItemGroup>

</Project>
